### ISSUE TITLE
AS A user, I WANT TO see a resource page

### ISSUE THREAD

**Issue by lulu-cao** [lulu-cao/cultivate-community#3]
- [x] When I go to the resource page, I can see the general resources
- [x] Add links for the following pages to resources:
- [x] [Al-Anon](https://al-anon.org/al-anon-meetings/find-an-al-anon-meeting/) 
- [x] [Nar-Anon ](https://www.nar-anon.org/)
- [x] [SMART Recovery](https://www.smartrecovery.org/family/)
- [x] [Nursing Drug Monitoring Program for NC](https://www.ncbon.com/discipline-compliance-drug-monitoring-programs)

**Comment by alepehernandez** [comment]
Added the links under General Resources > Other Resources.
